package selling

import (
	"gin-template/middleware"
	"gin-template/modules/selling/controller"

	"github.com/gin-gonic/gin"
)

func RegisterRoutes(parent *gin.RouterGroup) {
	loyaltyHandler := controller.NewLoyaltyProgramController()
	posHandler := controller.NewPOSController()
	posProfileHandler := controller.NewPOSProfileController()
	storeHandler := controller.NewStoreController()
	priceListHandler := controller.NewPriceListController()
	salesInvoiceHandler := controller.NewSalesInvoiceController()
	customerHandler := controller.NewCustomerController()
	customerMasterHandler := controller.NewCustomerMasterController()
	territoryHandler := controller.NewTerritoryController()
	salesPartnerHandler := controller.NewSalesPartnerController()
	itemGroupHandler := controller.NewItemGroupController()
	taxCategoryHandler := controller.NewTaxCategoryController()
	quotationHandler := controller.NewQuotationController()
	subscriptionHandler := controller.NewSubscriptionController()
	subscriptionPlanHandler := controller.NewSubscriptionPlanController()
	pricingRuleHandler := controller.NewPricingRuleController()

	store := parent.Group("/store")
	{
		store.POST("/auth/register", middleware.CriticalRateLimit(), storeHandler.Register)
		store.GET("/categories", storeHandler.Categories)
		store.GET("/products", storeHandler.Products)
		store.GET("/products/:slug", storeHandler.Product)
	}
	storeAccount := store.Group("")
	storeAccount.Use(middleware.UserAuth())
	{
		storeAccount.GET("/me", storeHandler.Me)
		storeAccount.PUT("/me", storeHandler.UpdateMe)
		storeAccount.GET("/cart", storeHandler.Cart)
		storeAccount.POST("/cart/:productID", storeHandler.AddCart)
		storeAccount.PUT("/cart/:productID", storeHandler.UpdateCart)
		storeAccount.DELETE("/cart/:productID", storeHandler.RemoveCart)
		storeAccount.GET("/wishlist", storeHandler.Wishlist)
		storeAccount.POST("/wishlist/:productID", storeHandler.AddWishlist)
		storeAccount.DELETE("/wishlist/:productID", storeHandler.RemoveWishlist)
		storeAccount.GET("/orders", storeHandler.Orders)
		storeAccount.POST("/orders", storeHandler.CreateOrder)
		storeAccount.GET("/orders/:id/payment-status", storeHandler.OrderPaymentStatus)
	}

	group := parent.Group("/selling")
	group.Use(middleware.AdminAuth())
	{
		group.GET("/loyalty-programs/options", loyaltyHandler.Options)
		group.GET("/loyalty-programs", loyaltyHandler.List)
		group.POST("/loyalty-programs", loyaltyHandler.Create)
		group.GET("/loyalty-programs/:id", loyaltyHandler.Get)
		group.PUT("/loyalty-programs/:id", loyaltyHandler.Update)
		group.DELETE("/loyalty-programs/:id", loyaltyHandler.Delete)
		group.GET("/loyalty-point-entries", loyaltyHandler.EntriesList)
		group.POST("/loyalty-point-entries", loyaltyHandler.CreateEntry)
		group.DELETE("/loyalty-point-entries/:id", loyaltyHandler.DeleteEntry)
		group.GET("/pos/opening-entries", posHandler.OpeningEntries)
		group.GET("/pos/opening-entries/current", posHandler.CurrentOpening)
		group.GET("/pos/opening-entries/:id", posHandler.GetOpeningEntry)
		group.GET("/pos/items", posHandler.Items)
		group.POST("/pos/opening-entries", posHandler.CreateOpening)
		group.POST("/pos/opening-entries/:id/close", posHandler.CloseOpening)
		group.GET("/pos/closing-entries", posHandler.ClosingEntries)
		group.GET("/pos/closing-entries/:id", posHandler.GetClosingEntry)
		group.GET("/pos/invoices", posHandler.Invoices)
		group.POST("/pos/invoices", posHandler.CreateInvoice)

		group.GET("/pos-profiles/options", posProfileHandler.Options)
		group.GET("/pos-profiles", posProfileHandler.List)
		group.GET("/pos-profiles/:id", posProfileHandler.Get)
		group.POST("/pos-profiles", posProfileHandler.Create)
		group.PUT("/pos-profiles/:id", posProfileHandler.Update)
		group.DELETE("/pos-profiles/:id", posProfileHandler.Delete)
		group.GET("/price-lists", priceListHandler.ListPriceLists)
		group.POST("/price-lists/seed", priceListHandler.Seed)
		group.GET("/price-lists/:id", priceListHandler.GetPriceList)
		group.POST("/price-lists", priceListHandler.CreatePriceList)
		group.PUT("/price-lists/:id", priceListHandler.UpdatePriceList)
		group.DELETE("/price-lists/:id", priceListHandler.DeletePriceList)
		group.GET("/item-prices", priceListHandler.ListItemPrices)
		group.GET("/item-prices/:id", priceListHandler.GetItemPrice)
		group.POST("/item-prices", priceListHandler.CreateItemPrice)
		group.PUT("/item-prices/:id", priceListHandler.UpdateItemPrice)
		group.DELETE("/item-prices/:id", priceListHandler.DeleteItemPrice)
		group.GET("/sales-invoices/options", salesInvoiceHandler.Options)
		group.GET("/sales-invoices", salesInvoiceHandler.List)
		group.POST("/sales-invoices", salesInvoiceHandler.Create)
		group.GET("/sales-invoices/:id", salesInvoiceHandler.Get)
		group.PUT("/sales-invoices/:id", salesInvoiceHandler.Update)
		group.POST("/sales-invoices/:id/submit", salesInvoiceHandler.Submit)
		group.POST("/sales-invoices/:id/cancel", salesInvoiceHandler.Cancel)
		group.POST("/sales-invoices/:id/return", salesInvoiceHandler.CreateReturn)
		group.POST("/sales-invoices/:id/mark-paid", salesInvoiceHandler.MarkPaid)
		group.POST("/sales-invoices/:id/refund", salesInvoiceHandler.Refund)
		group.DELETE("/sales-invoices/:id", salesInvoiceHandler.Delete)
		group.GET("/customers", customerHandler.List)
		group.POST("/customers", customerHandler.Create)
		group.GET("/customers/:id", customerHandler.Get)
		group.PUT("/customers/:id", customerHandler.Update)
		group.DELETE("/customers/:id", customerHandler.Delete)
		group.GET("/customer-groups", customerMasterHandler.ListCustomerGroups)
		group.POST("/customer-groups", customerMasterHandler.CreateCustomerGroup)
		group.GET("/customer-groups/:id", customerMasterHandler.GetCustomerGroup)
		group.PUT("/customer-groups/:id", customerMasterHandler.UpdateCustomerGroup)
		group.DELETE("/customer-groups/:id", customerMasterHandler.DeleteCustomerGroup)
		group.GET("/addresses", customerMasterHandler.ListAddresses)
		group.POST("/addresses", customerMasterHandler.CreateAddress)
		group.GET("/addresses/:id", customerMasterHandler.GetAddress)
		group.PUT("/addresses/:id", customerMasterHandler.UpdateAddress)
		group.DELETE("/addresses/:id", customerMasterHandler.DeleteAddress)
		group.GET("/contacts", customerMasterHandler.ListContacts)
		group.POST("/contacts", customerMasterHandler.CreateContact)
		group.GET("/contacts/:id", customerMasterHandler.GetContact)
		group.PUT("/contacts/:id", customerMasterHandler.UpdateContact)
		group.DELETE("/contacts/:id", customerMasterHandler.DeleteContact)
		group.GET("/territories/options", territoryHandler.Options)
		group.GET("/territories/tree", territoryHandler.Tree)
		group.GET("/territories", territoryHandler.List)
		group.POST("/territories", territoryHandler.Create)
		group.GET("/territories/:id", territoryHandler.Get)
		group.PUT("/territories/:id", territoryHandler.Update)
		group.DELETE("/territories/:id", territoryHandler.Delete)
		group.GET("/sales-partner-types", salesPartnerHandler.ListPartnerTypes)
		group.POST("/sales-partner-types", salesPartnerHandler.CreatePartnerType)
		group.GET("/item-groups/tree", itemGroupHandler.Tree)
		group.GET("/item-groups", itemGroupHandler.List)
		group.POST("/item-groups", itemGroupHandler.Create)
		group.GET("/item-groups/:id", itemGroupHandler.Get)
		group.PUT("/item-groups/:id", itemGroupHandler.Update)
		group.DELETE("/item-groups/:id", itemGroupHandler.Delete)
		group.GET("/fiscal-years", salesPartnerHandler.ListFiscalYears)
		group.POST("/fiscal-years", salesPartnerHandler.CreateFiscalYear)
		group.GET("/sales-partners/options", salesPartnerHandler.Options)
		group.GET("/sales-partners", salesPartnerHandler.List)
		group.POST("/sales-partners", salesPartnerHandler.Create)
		group.GET("/sales-partners/:id", salesPartnerHandler.Get)
		group.PUT("/sales-partners/:id", salesPartnerHandler.Update)
		group.DELETE("/sales-partners/:id", salesPartnerHandler.Delete)
		group.GET("/tax-categories", taxCategoryHandler.List)
		group.POST("/tax-categories", taxCategoryHandler.Create)
		group.GET("/tax-categories/:id", taxCategoryHandler.Get)
		group.PUT("/tax-categories/:id", taxCategoryHandler.Update)
		group.DELETE("/tax-categories/:id", taxCategoryHandler.Delete)
		group.GET("/quotations", quotationHandler.List)
		group.POST("/quotations", quotationHandler.Create)
		group.GET("/quotations/:id", quotationHandler.Get)
		group.PUT("/quotations/:id", quotationHandler.Update)
		group.DELETE("/quotations/:id", quotationHandler.Delete)
		group.GET("/subscriptions", subscriptionHandler.List)
		group.POST("/subscriptions", subscriptionHandler.Create)
		group.GET("/subscriptions/:id", subscriptionHandler.Get)
		group.PUT("/subscriptions/:id", subscriptionHandler.Update)
		group.DELETE("/subscriptions/:id", subscriptionHandler.Delete)
		group.GET("/subscription-plans", subscriptionPlanHandler.List)
		group.POST("/subscription-plans", subscriptionPlanHandler.Create)
		group.GET("/subscription-plans/:id", subscriptionPlanHandler.Get)
		group.PUT("/subscription-plans/:id", subscriptionPlanHandler.Update)
		group.DELETE("/subscription-plans/:id", subscriptionPlanHandler.Delete)
		group.GET("/pricing-rules", pricingRuleHandler.ListPricingRules)
		group.POST("/pricing-rules", pricingRuleHandler.CreatePricingRule)
		group.GET("/pricing-rules/:id", pricingRuleHandler.GetPricingRule)
		group.PUT("/pricing-rules/:id", pricingRuleHandler.UpdatePricingRule)
		group.DELETE("/pricing-rules/:id", pricingRuleHandler.DeletePricingRule)
	}
}
