/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as KelasCourseIdRouteImport } from './routes/kelas/$courseId'

const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasCourseIdRoute = KelasCourseIdRouteImport.update({
  id: '/kelas/$courseId',
  path: '/kelas/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/harga': typeof HargaRoute
  '/pembayaran': typeof PembayaranRoute
  '/kelas/$courseId': typeof KelasCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/harga': typeof HargaRoute
  '/pembayaran': typeof PembayaranRoute
  '/kelas/$courseId': typeof KelasCourseIdRoute
  '/payments': typeof PaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/harga': typeof HargaRoute
  '/pembayaran': typeof PembayaranRoute
  '/kelas/$courseId': typeof KelasCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivasi'
    | '/harga'
    | '/pembayaran'
    | '/kelas/$courseId'
    | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivasi'
    | '/harga'
    | '/pembayaran'
    | '/kelas/$courseId'
    | '/payments'
  id:
    | '__root__'
    | '/'
    | '/aktivasi'
    | '/harga'
    | '/pembayaran'
    | '/kelas/$courseId'
    | '/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivasiRoute: typeof AktivasiRoute
  HargaRoute: typeof HargaRoute
  PembayaranRoute: typeof PembayaranRoute
  KelasCourseIdRoute: typeof KelasCourseIdRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas/$courseId': {
      id: '/kelas/$courseId'
      path: '/kelas/$courseId'
      fullPath: '/kelas/$courseId'
      preLoaderRoute: typeof KelasCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivasiRoute: AktivasiRoute,
  HargaRoute: HargaRoute,
  PembayaranRoute: PembayaranRoute,
  KelasCourseIdRoute: KelasCourseIdRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
