/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ProductsCourseIdRouteImport } from './routes/products/$courseId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCourseIdRoute = ProductsCourseIdRouteImport.update({
  id: '/products/$courseId',
  path: '/products/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aktivasi': typeof AktivasiRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pembayaran': typeof PembayaranRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aktivasi': typeof AktivasiRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pembayaran': typeof PembayaranRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments': typeof PaymentsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aktivasi': typeof AktivasiRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/pembayaran': typeof PembayaranRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/aktivasi'
    | '/checkout'
    | '/login'
    | '/pembayaran'
    | '/product/$slug'
    | '/products/$courseId'
    | '/payments/'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/aktivasi'
    | '/checkout'
    | '/login'
    | '/pembayaran'
    | '/product/$slug'
    | '/products/$courseId'
    | '/payments'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/aktivasi'
    | '/checkout'
    | '/login'
    | '/pembayaran'
    | '/product/$slug'
    | '/products/$courseId'
    | '/payments/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AktivasiRoute: typeof AktivasiRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PembayaranRoute: typeof PembayaranRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsCourseIdRoute: typeof ProductsCourseIdRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$courseId': {
      id: '/products/$courseId'
      path: '/products/$courseId'
      fullPath: '/products/$courseId'
      preLoaderRoute: typeof ProductsCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AktivasiRoute: AktivasiRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PembayaranRoute: PembayaranRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsCourseIdRoute: ProductsCourseIdRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
