/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as ProductsCourseIdRouteImport } from './routes/products/$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCourseIdRoute = ProductsCourseIdRouteImport.update({
  id: '/products/$courseId',
  path: '/products/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/pembayaran': typeof PembayaranRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/pembayaran': typeof PembayaranRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments': typeof PaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/pembayaran': typeof PembayaranRoute
  '/products/$courseId': typeof ProductsCourseIdRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/aktivasi' | '/pembayaran' | '/products/$courseId' | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aktivasi' | '/pembayaran' | '/products/$courseId' | '/payments'
  id:
    | '__root__'
    | '/'
    | '/aktivasi'
    | '/pembayaran'
    | '/products/$courseId'
    | '/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivasiRoute: typeof AktivasiRoute
  PembayaranRoute: typeof PembayaranRoute
  ProductsCourseIdRoute: typeof ProductsCourseIdRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$courseId': {
      id: '/products/$courseId'
      path: '/products/$courseId'
      fullPath: '/products/$courseId'
      preLoaderRoute: typeof ProductsCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivasiRoute: AktivasiRoute,
  PembayaranRoute: PembayaranRoute,
  ProductsCourseIdRoute: ProductsCourseIdRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
